services:
  oraclellg:
    image: gvenzl/oracle-xe:11.2.0.2-full
    container_name: oracle11g
    restart: unless-stopped               # 宿主机重启后自动拉起

    # 端口映射
    ports:
      - "1521:1521"   # 数据库监听
      - "5500:5500"   # EM Express（如果用得到，可保留）

    # 关键环境变量
    environment:
      # SYSTEM 密码（必填）
      ORACLE_PASSWORD: oracle123
      # ▶ 以下均为可选，按需开启 ◀
      # 首启时直接创建一个业务 PDB（仅 21c/18c 有效，11g 可忽略）
      # ORACLE_DATABASE: ORCL
      # 自动建业务用户
      # APP_USER: devuser
      # APP_USER_PASSWORD: dev123

    # 数据文件持久化（匿名卷也行，建议显式声明）
    volumes:
      - oracle-data:/opt/oracle/oradata   

# 声明命名卷，Docker 会自动创建
volumes:
  oracle-data: